### ISSUE TITLE
Log message does not correlate with the trace when trace_id and spand_id are included

### ISSUE THREAD

**Issue by IvanRublev** [spandex-project/spandex#118]
### What's now:
Having the following lines in `config.exs`
```
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id, :trace_id, :span_id]
```
The trace produced with no logs associated
![Screenshot 2020-09-11 at 11 26 54](https://user-images.githubusercontent.com/5757941/92904021-d2beb380-f422-11ea-87a4-af42693f0e2a.png)

same time the trace id and span id are included in the log message.
![Screenshot 2020-09-11 at 11 28 03](https://user-images.githubusercontent.com/5757941/92904080-dd794880-f422-11ea-8a2f-139100ab5c97.png)

Seems the format of log message is wrong, it should be `dd.trace_id` and `dd.span_id` according to [the docs](https://docs.datadoghq.com/tracing/connect_logs_and_traces/)

### What's expected

Log record is correlated and visible on the trace page.

**Comment by hkrutzer** [comment]
You should log as JSON and then configure trace id mapping in the pipeline configuration
<img width="541" alt="image" src="https://user-images.githubusercontent.com/3464899/92909566-89bd2e00-f427-11ea-9b39-e409f4aaa714.png">

**Comment by GregMefford** [comment]
There is also a place to do this globally, if you don't want to do it specifically for a particular pipeline. It's in the log configuration right after "Ingest API," before all the pipelines.

Please let us know if this fixes it for you! We're just now getting DD Logs set up where I work, so we haven't hit these kinds of issues yet in "real life."

https://app.datadoghq.com/logs/pipelines/remapping

![image](https://user-images.githubusercontent.com/69467/92929591-caf51400-f40e-11ea-9110-c8522ffa6a26.png)
