### ISSUE TITLE
Spandex.finish_{span,trace} don't update traces before completing

### ISSUE THREAD

**Issue by GregMefford** [spandex-project/spandex#64]
Maybe this was intentional, but while I was working on tests for the functions in the `Spandex` module, I noticed that if you pass in a `completion_time` when you call `Spandex.finish_span`, it is ignored. If you call `Spandex.update_span` with that option just before calling `Spandex.finish_span`, then it is updated. We should think about whether it makes sense to warn/log/error when you pass in unsupported opts that are going to get ignored.

**Comment by zachdaniel** [comment]
Yeah, I think it's just a bug that we don't update the span from the opts.

**Comment by zachdaniel** [comment]
Resolved by #88
