### ISSUE TITLE
Documentation could use 1 additional line at the beginning

### ISSUE THREAD

**Issue by AntonTrapp** [spandex-project/spandex#83]
1st questions when I opened this project "What does it do? What is it good for?" ;)

**Comment by GregMefford** [comment]
Haha, thanks for the feedback! I had planned to make a pass over the docs for some recent changes, so I’ll clarify that as well. :thumbsup: :rocket:

**Comment by AntonTrapp** [comment]
Great, seams to be a very useful peace of software - would be a shame if some people would miss it...

**Comment by zachdaniel** [comment]
Closed via: 9feff65d2ea8e823dc753bbf642526b1a678ce5b
