### ISSUE TITLE
Datadog Tags

### ISSUE THREAD

**Issue by ludwikbukowski** [spandex-project/spandex#85]
Is there possibility to add [Datadog's tags](https://docs.datadoghq.com/tagging/) into Traces?
So that except the metadata in the span, we `tag` the span, e.g with `result:success`

**Comment by ludwikbukowski** [comment]
Ok, I found it. Just couldn't find in the documentation:
https://github.com/spandex-project/spandex_datadog/blob/master/lib/spandex_datadog/api_server.ex#L305

**Comment by GregMefford** [comment]
Yep, sorry that wasn’t clear! The docs in the README could use some more details in several areas.
